### ISSUE TITLE
Incorrect install instructions

### ISSUE THREAD

**Issue by chibbs96** [LearnDeepMilwaukee/valuenetwork#1]
install.txt in /docs/install.txt instructs to download the incorrect git repository.

Step #6:
```
6. clone the valuenetwork repo inside the vn virtualenv.
git clone https://github.com/FreedomCoop/valuenetwork.git
```

Link should be `https://github.com/LearnDeepMilwaukee/valuenetwork.git`

**Comment by bhaugen** [comment]
Fixed by https://github.com/LearnDeepMilwaukee/valuenetwork/commit/86815c131187e35e7ea75bb94f9299839c0d524b
