### ISSUE TITLE
Faceted classification for resources

### ISSUE THREAD

**Issue by fosterlynn** [LearnDeepMilwaukee/valuenetwork#10]
This was discussed as part of a solution for people being able to search in inventory for resources they might be interested in.

I started the work, but need to know how you want to use them.  And for sure if you want to use them, for that matter.  :)  

The django app has filtering capability by facet value.  It looks like this (test data only):

![fv-filter](https://user-images.githubusercontent.com/3776081/35452488-3ea0fa3a-028c-11e8-9b42-fee04449af00.png)

What api queries I create will depend on how the new UI will work for search/filter.

Note: This will also require assigning facet values when the resource type is created.  Creation of resource types (classifications) is not yet part of the react inventory app, so all of that would continue to happen on the backend for now.

@pdreyn and team, let's discuss.

**Comment by pdreyn** [comment]
Yes, we will want the facets, I can see that as being key to easily finding stuff.

In terms of "how you want to use them"  what are the options that would impact how you would approach it?

**Comment by fosterlynn** [comment]
Well, I could create something in the api that works just like the django app, where you can choose one or more facet values, and it can bring back a collection of resources.  I just wasn't sure if there were other ideas on how finding resources would work best for you all.  

I can provide that, and then we can see how that interface develops in terms of new ideas.

**Comment by pdreyn** [comment]
that works for me, thx!

**Comment by fosterlynn** [comment]
OK will do.  Closing the issue.
